cc_binary(
    name = "hello_world",
    srcs = [
        "hello.cpp",
    ],
    deps = [
        ":greeting",
    ],
)

cc_library(
    name = "greeting",
    srcs = [
        "greeting.cc",
    ],
    hdrs = [
        "greeting.h",
    ],
  )
